# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Gatsby Application Build and Deployment

on:
  push:
    branches: 
      main
      

jobs:
  build-and-deploy:
    name: Build and Deploy Gatsby Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        users: actions/setup-node@v1
        with:
          

  
